### ISSUE TITLE
unit of measurement wrong for homeassistant

### ISSUE THREAD

**Issue by patsch9** [gluap/pyess#14]
Hi,

In essmqtt.py there is a wrong attribute:

    if "enegy" in sensor or "energy" in sensor:  # typo in ess json
        description["**unit_of_measuremnt**"] = "Wh"
        description["icon"] = "mdi:gauge"

please set it to 
    if "enegy" in sensor or "energy" in sensor:  # typo in ess json
        description["unit_of_measurem**e**nt"] = "Wh"
        description["icon"] = "mdi:gauge"

Thanks for the great work!

Patrick

**Comment by gluap** [comment]
Hi Patrick,

this should be fixed by the latest changes, thank you for reporting this (and delivering the solution in the issue)!

Cheers,
PAul

**Comment by patsch9** [comment]
Great! Thanks for fixing
