### ISSUE TITLE
try to use with new resu system

### ISSUE THREAD

**Issue by Alessandro1983** [gluap/pyess#24]
Hi, i try to use this method with new LG resu system, but nothing happen, in terminal this is the result:
  File "ess.py", line 64
    def get_graph(self, device: str, timespan: str, date: datetime.datetime):

**Comment by gluap** [comment]
Is that system still using the old EnerVu app? If not very likely it doesn't use the API for that app.

**Comment by Alessandro1983** [comment]
no unfotunately the system doesn't use enervu app it's called LGES eMonitoring
