### ISSUE TITLE
No module named 'aiomqtt.error'

### ISSUE THREAD

**Issue by meschmesch** [gluap/pyess#25]
Hi, 
after an upgrade my Rhaspberry Pi 4 to the latest Debian Bookworm version, I had to reinstall pyess. Installation via virtual environment runs without problems. But the test fails:

`pi@raspberry2:~/pyess/bin $ ./essmqtt --mqtt_server 192.168.2.115 --ess_host=192.168.176.3 --ess_password mypassword
Traceback (most recent call last):
  File "/home/pi/pyess/bin/./essmqtt", line 5, in <module>
    from pyess.essmqtt import main
  File "/home/pi/pyess/lib/python3.11/site-packages/pyess/essmqtt.py", line 9, in <module>
    import aiomqtt.error
ModuleNotFoundError: No module named 'aiomqtt.error'
`

I tried to reinstall aiomqtt via `pip install aiomqtt` but the error doesn't vanish. Any idea? Thank you!

**Comment by gluap** [comment]
Thank you for the heads-up.

Aiomqtt changed their API on Jan 15th. I enforced using their older, still compatible version until I can get around to adapting to the changes. Try pyess-0.1.21.

**Comment by meschmesch** [comment]
So I just installed it again with `pip install pyess` and thanks to your fix it works again. Thank you!
