### ISSUE TITLE
Typo still needs fixing

### ISSUE THREAD

**Issue by tvilhu** [gluap/pyess#26]
There was earlier fix to json typo in essmqtt.py

if "enegy" in sensor or "energy" in sensor or sensor.endswith("_sum"):  # typo in ess json

but this does not fix the issue since there is typo in the fix afaik. The typo in ess json is "enery" not "enegy". I am not sure if this "enegy" typo exists but it would be possible to fix this changing code to 

if "enegy" in sensor or "enery" in sensor or "energy" in sensor or sensor.endswith("_sum"):  # typo in ess json

**Comment by gluap** [comment]
You're right, both ``enery`` and ``enegy`` typos are present in the json...
```
ess/common/LOAD/today_pv_direct_consumption_enegy 0
ess/common/LOAD/today_batt_discharge_enery 135
```
seriously who has done QA on that API at LG?.
