### ISSUE TITLE
Addon is crashing daily

### ISSUE THREAD

**Issue by aLimp86** [gluap/pyess#29]
Hi all, since 3 days the LG ESS Addon is crashing daily (on different timestamps) on my raspberry pi 4. It worked flawlessly until this date. 
It must be caused by the 2024.06.x update. 

I have the following version:
Core 2024.6.1
Supervisor 2024.06.0
OS 12.3
Frontend 20240605.0 

Edit 2024-06-09: *deleted the error text because this was misleading and the wrong one* 
I always have to start the Addon manually again. Even the watchdog does not do his thing. 
I've created an automation to start the Addon again 2min after crashing. Did not work tonight.

**Comment by gluap** [comment]
How do you notice its crashing apart from the error message? 

The error seems to be from a template dividing daily values and independent from pyess - and the error happening shortly after midnight makes me think that the denominator of that fraction causing the error may well be zero. At midnight the daily values reported by ess reset to zero.

**Comment by aLimp86** [comment]
I've activated the binary sensor "lg_ess_running" entity from the Addon. As soon as this state goes to "not running" I get a notification on my phone. 
I think this error message is just a result from the Addon crashing. 

The days before it happened also during the day. So division by zero is not causing the crash.

**Comment by gluap** [comment]
could you check the "log" tab of the pyess-addon after such a crash? The output should contain some details on what happened.

**Comment by gluap** [comment]
Looks like this for me 
![image](https://github.com/gluap/pyess/assets/44007906/8346ab5c-998f-4d99-8216-b2f5ca70b083)

**Comment by aLimp86** [comment]
It crashed again and seems not to be able to recover. This is the error message:
![image](https://github.com/gluap/pyess/assets/130318612/b454970b-4c6b-4363-a2c2-bfed2aeb3530)

**Comment by aLimp86** [comment]
Or few minutes before it looked like this and was also not starting. 
![image](https://github.com/gluap/pyess/assets/130318612/45efd439-8eb6-400c-86bf-1f3cfc0df923)

**Comment by aLimp86** [comment]
Ok, found something. As soon as the LG ESS Addon is crashing my complete LG ESS HOME 10 System is losing the network connection to my home network. This is strange and I don't know why. Nothing was changed. 
But it is not related to the Addon itself. Topic can be closed.

**Comment by gluap** [comment]
You could try to assign a static ip to your ess (for instance by configuring it in your router or in the ess connection settings) and configure that ip explicitly in pyess-addon. The error loooks like it iss happening when the connection is lost and pyess tries to search the network for the ESS which hasn't come back up yet. I'm not sure but it might deal with that situation more gracefully if a static ip is used.
